spring:
  application:
    name: attoly-api
  security:
    oauth2:
      client:
        registration:
          github:
            scope:
              - user:email
              - read:user
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  messages:
    basename: messages/validation, messages/error, messages/mail
    encoding: UTF-8
    fallback-to-system-locale: false
attoly:
  scheduling:
    jobs:
      role-seeding:
        enabled: true
